port: 25565
server_name: "MCarmada Test"
server_motd: "Test MotD"
public: true
verify_names: false
max_players: 32
broadcast: true
whitelist: true
world:
    width: 128
    depth: 128
    height: 128
    generator: classic
    water_flow: true
    lava_flow: true
    grow_trees: true
    block_fall: true