port: 25565
server_name: "MCarmada Test"
server_motd: "&eMCarmada rules!"
public: true
verify_names: false
max_players: 32
broadcast: true
whitelist: true
world:
    name: test3
    width: 64
    depth: 64
    height: 64
    generator: classic
    water_flow: true
    lava_flow: true
    grow_trees: true
    block_fall: true
    enable_save: true