port: 25565
server_name: "MCarmada Test"
server_motd: "Test MotD"
public: false
verify_names: false
max_players: 32
broadcast: false
world:
    width: 64
    depth: 64
    height: 64
    generator: classic